### ISSUE TITLE
mig-controller-rest pod CrashLoopBackOff

### ISSUE THREAD

**Issue by stoneshi-yunify** [jibutech/backup-saas-client#103]
```
root@i-k70jhesn:~# kubectl -n backup-worker-3 get pod
NAME                                   READY   STATUS             RESTARTS   AGE
backup-worker-3-c6c687599-gr7cm        2/2     Running            0          13h
mig-controller-rest-5557698778-6sbcb   0/1     CrashLoopBackOff   99         13h
ui-discovery-rest-685884cd6c-66q6g     1/1     Running            0          13h
```

```
root@i-k70jhesn:~# kubectl -n backup-worker-3 logs pod mig-controller-rest-5557698778-6sbcb --tail=100
Error from server (NotFound): pods "pod" not found
root@i-k70jhesn:~# kubectl -n backup-worker-3 logs mig-controller-rest-5557698778-6sbcb --tail=100
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:227
2022-01-21T02:20:24.359Z	ERROR	controllers.Restore.Restore	validate pv error	{"error": "source cluster isn't ready for restore test1124, <nil>"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:227
2022-01-21T02:20:24.371Z	ERROR	controllers.Restore.Restore	validate pv error	{"error": "Backup.migration.yinhestor.com \"ks-devops-backup\" not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:227
2022-01-21T02:20:24.381Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "390970484109350327", "storage": "373292893059738374"}
2022-01-21T02:20:24.381Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "376906303085275808", "storage": "373292893059738374"}
2022-01-21T02:20:24.381Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "373292869286423302", "storage": "373292893059738374"}
2022-01-21T02:20:24.381Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "384059335866586514", "storage": "373292893059738374"}
2022-01-21T02:20:25.052Z	ERROR	controllers.Restore.Restore	validate pv error	{"error": "source cluster isn't ready for restore test-client-side, &{{MigCluster migration.yinhestor.com/v1alpha1} {384059335866586514  backup-tenant-1 /apis/migration.yinhestor.com/v1alpha1/namespaces/backup-tenant-1/migclusters/384059335866586514 ac067609-7ed6-44f6-b46c-7618f6fb0cdb 537098869 56 2021-12-02 12:07:27 +0000 UTC <nil> <nil> map[] map[yinhestor.com/touch:0704d0db-7a5d-11ec-8eff-2aa3b715e488] [{ys.jibudata.com/v1alpha1 Cluster 384059335866586514 49c046a0-38c6-41ea-81f1-6bdca55fc826 <nil> <nil>}] []  [{manager Update migration.yinhestor.com/v1alpha1 2021-12-02 12:07:31 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:yinhestor.com/touch\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"49c046a0-38c6-41ea-81f1-6bdca55fc826\\\"}\":{\".\":{},\"f:apiVersion\":{},\"f:kind\":{},\"f:name\":{},\"f:uid\":{}}}},\"f:spec\":{\".\":{},\"f:insecure\":{},\"f:isHostCluster\":{},\"f:location\":{\".\":{},\"f:isOnPublicCloud\":{},\"f:provider\":{}},\"f:serviceAccountSecretRef\":{\".\":{},\"f:name\":{},\"f:namespace\":{}},\"f:storageClasses\":{},\"f:url\":{}},\"f:status\":{\".\":{},\"f:conditions\":{},\"f:isInService\":{},\"f:observedDigest\":{}}}}]} {false false https://139.198.15.193:36443 &ObjectReference{Kind:,Namespace:backup-tenant-1,Name:384059335866586514-token,UID:,APIVersion:,ResourceVersion:,FieldPath:,} [] [{csi-hostpath-sc hostpath.csi.k8s.io true [ReadWriteOnce]} {local openebs.io/local false [ReadWriteOnce]}] []  true <nil> 0xc0051dc940 } {{[{TestConnectFailed True ConnectFailed Critical Test connect failed. : Unauthorized 2022-01-07 03:44:38 +0000 UTC false [] false}] false} 9caa47338b8a3bd281f0be7cff89cfcdafda14752d3e4b0c72bfb6a6b1ab1b6c true []}}"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:227
2022-01-21T02:20:25.059Z	ERROR	controllers.Restore.Restore	validate pv error	{"error": "Backup.migration.yinhestor.com \"test0918\" not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:227
2022-01-21T02:20:25.069Z	ERROR	controllers.Restore.Restore	validate pv error	{"error": "source cluster isn't ready for restore test1123, <nil>"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:227
2022-01-21T02:20:25.077Z	ERROR	controllers.Restore.Restore	validate pv error	{"error": "Backup.migration.yinhestor.com \"test0929\" not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:227
2022-01-21T02:20:25.083Z	ERROR	controllers.Restore.Restore	validate pv error	{"error": "source cluster isn't ready for restore test-watch, <nil>"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:227
2022-01-21T02:20:25.268Z	INFO	controller.backupjob	pending deletion since there are dependant ongoing restorejobs	{"reconciler group": "migration.yinhestor.com", "reconciler kind": "BackupJob", "name": "hehe-i5zc6", "namespace": "backup-tenant-369641743475338021", "Request.Namespace": "backup-tenant-369641743475338021", "Request.Name": "hehe-i5zc6", "counts": 1}
2022-01-21T02:20:25.390Z	INFO	controllers.MigCluster	Starting remote watch.	{"cluster": "390957162278426039"}
2022-01-21T02:20:25.468Z	INFO	controller.backupjob	pending deletion since there are dependant ongoing restorejobs	{"reconciler group": "migration.yinhestor.com", "reconciler kind": "BackupJob", "name": "backup-20211201163353-m74ba", "namespace": "backup-tenant-369641743475338021", "Request.Namespace": "backup-tenant-369641743475338021", "Request.Name": "backup-20211201163353-m74ba", "counts": 1}
2022-01-21T02:20:25.549Z	INFO	controller.backupjob	pending deletion since there are dependant ongoing restorejobs	{"reconciler group": "migration.yinhestor.com", "reconciler kind": "BackupJob", "name": "backup-20211201141743-5okcn", "namespace": "backup-tenant-369641743475338021", "Request.Namespace": "backup-tenant-369641743475338021", "Request.Name": "backup-20211201141743-5okcn", "counts": 1}
2022-01-21T02:20:25.594Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "373853805806152367", "storage": "388787608001451450"}
2022-01-21T02:20:25.648Z	INFO	controller.backupjob	pending deletion since there are dependant ongoing restorejobs	{"reconciler group": "migration.yinhestor.com", "reconciler kind": "BackupJob", "name": "ks-monitor-bb-fn4c3", "namespace": "backup-tenant-369641743475338021", "Request.Namespace": "backup-tenant-369641743475338021", "Request.Name": "ks-monitor-bb-fn4c3", "counts": 1}
2022-01-21T02:20:25.692Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "390970484109350327", "storage": "388787608001451450"}
2022-01-21T02:20:25.692Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "376906303085275808", "storage": "388787608001451450"}
2022-01-21T02:20:25.692Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "373292869286423302", "storage": "388787608001451450"}
2022-01-21T02:20:25.692Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "384059335866586514", "storage": "388787608001451450"}
2022-01-21T02:20:25.707Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "376906303085275808", "storage": "377071868655495868"}
2022-01-21T02:20:25.707Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "373292869286423302", "storage": "377071868655495868"}
2022-01-21T02:20:25.707Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "384059335866586514", "storage": "377071868655495868"}
2022-01-21T02:20:25.719Z	INFO	controller.backupjob	pending deletion since there are dependant ongoing restorejobs	{"reconciler group": "migration.yinhestor.com", "reconciler kind": "BackupJob", "name": "backup-20211201132815-euqgr", "namespace": "backup-tenant-369641743475338021", "Request.Namespace": "backup-tenant-369641743475338021", "Request.Name": "backup-20211201132815-euqgr", "counts": 1}
2022-01-21T02:20:25.823Z	INFO	controller.backupjob	pending deletion since there are dependant ongoing restorejobs	{"reconciler group": "migration.yinhestor.com", "reconciler kind": "BackupJob", "name": "kubeedge-backup-8i7lw", "namespace": "backup-tenant-369641743475338021", "Request.Namespace": "backup-tenant-369641743475338021", "Request.Name": "kubeedge-backup-8i7lw", "counts": 1}
2022-01-21T02:20:25.869Z	INFO	controller.backupjob	pending deletion since there are dependant ongoing restorejobs	{"reconciler group": "migration.yinhestor.com", "reconciler kind": "BackupJob", "name": "backup-nginx-ucexs", "namespace": "backup-tenant-369641743475338021", "Request.Namespace": "backup-tenant-369641743475338021", "Request.Name": "backup-nginx-ucexs", "counts": 1}
2022-01-21T02:20:25.917Z	INFO	controller.backupjob	pending deletion since there are dependant ongoing restorejobs	{"reconciler group": "migration.yinhestor.com", "reconciler kind": "BackupJob", "name": "istio-backup-faukk", "namespace": "backup-tenant-369641743475338021", "Request.Namespace": "backup-tenant-369641743475338021", "Request.Name": "istio-backup-faukk", "counts": 1}
2022-01-21T02:20:25.972Z	INFO	controller.backupjob	pending deletion since there are dependant ongoing restorejobs	{"reconciler group": "migration.yinhestor.com", "reconciler kind": "BackupJob", "name": "jj-lnnj8", "namespace": "backup-tenant-369641743475338021", "Request.Namespace": "backup-tenant-369641743475338021", "Request.Name": "jj-lnnj8", "counts": 1}
2022-01-21T02:20:26.022Z	INFO	controller.backupjob	pending deletion since there are dependant ongoing restorejobs	{"reconciler group": "migration.yinhestor.com", "reconciler kind": "BackupJob", "name": "hhh-dgbak", "namespace": "backup-tenant-369641743475338021", "Request.Namespace": "backup-tenant-369641743475338021", "Request.Name": "hhh-dgbak", "counts": 1}
2022-01-21T02:20:26.072Z	INFO	controller.backupjob	pending deletion since there are dependant ongoing restorejobs	{"reconciler group": "migration.yinhestor.com", "reconciler kind": "BackupJob", "name": "ttt-jld6b", "namespace": "backup-tenant-369641743475338021", "Request.Namespace": "backup-tenant-369641743475338021", "Request.Name": "ttt-jld6b", "counts": 1}
2022-01-21T02:20:26.099Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "373853805806152367", "storage": "377071868655495868"}
2022-01-21T02:20:26.114Z	INFO	KubeAPIWarningLogger	batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
2022-01-21T02:20:26.121Z	INFO	controller.backupjob	pending deletion since there are dependant ongoing restorejobs	{"reconciler group": "migration.yinhestor.com", "reconciler kind": "BackupJob", "name": "default-backup-xqg9g", "namespace": "backup-tenant-369641743475338021", "Request.Namespace": "backup-tenant-369641743475338021", "Request.Name": "default-backup-xqg9g", "counts": 1}
2022-01-21T02:20:26.161Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "390970484109350327", "storage": "377071868655495868"}
2022-01-21T02:20:26.170Z	INFO	controller.backupjob	backupjob expired	{"reconciler group": "migration.yinhestor.com", "reconciler kind": "BackupJob", "name": "dd-1641492014", "namespace": "backup-tenant-369641743475338021", "Request.Namespace": "backup-tenant-369641743475338021", "Request.Name": "dd-1641492014", "now": "2022-01-21T02:20:26.170Z"}
2022-01-21T02:20:26.174Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "376906303085275808", "storage": "388246034553247153"}
2022-01-21T02:20:26.174Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "373292869286423302", "storage": "388246034553247153"}
2022-01-21T02:20:26.174Z	INFO	storage-provider	cluster is not ready, bypassing ensure BSL for storage	{"cluster": "384059335866586514", "storage": "388246034553247153"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ddf5ee]

goroutine 1315 [running]:
github.com/jibudata/mig-controller/controllers.(*BackupJobReconciler).deleteBackupResources(0xc00083fa10, 0xc00351cd20, 0x11, 0xc001a889c0)
	/workspace/controllers/backupjob_controller.go:421 +0xce
github.com/jibudata/mig-controller/controllers.(*BackupJobReconciler).Reconcile(0xc00083fa10, 0x2789000, 0xc0055e85d0, 0xc000c2e1c0, 0x20, 0xc000d57390, 0xd, 0xc0055e8500, 0x0, 0x0, ...)
	/workspace/controllers/backupjob_controller.go:145 +0x737
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0008a4460, 0x2789000, 0xc0055e8540, 0xc000c2e1c0, 0x20, 0xc000d57390, 0xd, 0xc0055e8500, 0x0, 0x0, ...)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:114 +0x247
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0008a4460, 0x2788f40, 0xc000b58180, 0x21be240, 0xc005f67ae0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:311 +0x30e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0008a4460, 0x2788f40, 0xc000b58180, 0x250d800)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc0055183c0, 0xc0008a4460, 0x2788f40, 0xc000b58180)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:227 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:223 +0x46b
```

this worker controls my tenant, and my cluster stuck in notready.

**Comment by stoneshi-yunify** [comment]
fixed
